version: '3.8'

name: eks-demo

services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    # ports:
    #   - '${AUTH_PORT}:${AUTH_PORT}'
    env_file:
      - .env

  user:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
    # ports:
    #   - '${USER_PORT}:${USER_PORT}'
    env_file:
      - .env

  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    # ports:
    #   - '${ADMIN_PORT}:${ADMIN_PORT}'
    env_file:
      - .env
