apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-test
  region: eu-west-1

availabilityZones:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c

managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true
    minSize: 1
    maxSize: 3
    volumeSize: 70
    ssh:
      allow: true
      publicKeyName: eks-keypair
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        albIngress: true

addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs: []
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest
  - name: aws-ebs-csi-driver
