kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "user-chart.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
data:
  USER_PORT: {{ .Values.service.targetPort | quote }}
  MONGODB_HOST: {{ .Values.db.MONGODB_HOST | quote }}
  MONGODB_USERNAME: {{ .Values.db.MONGODB_USERNAME | quote }}
  MONGODB_PASSWORD: {{ .Values.db.MONGODB_PASSWORD | quote }}
  MONGODB_DATABASE: {{ .Values.db.MONGODB_DATABASE | quote }}