name: Build and Push Docker Images

on:
  workflow_dispatch:

env:
  REPOSITORY: kenechukwujosiah

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git SHA
        id: vars
        run: echo "SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and Push Admin Image
        run: |
          docker build -t ${{env.REPOSITORY}}/eks-admin-demo:latest -t ${{env.REPOSITORY}}/eks-admin-demo:${{ steps.vars.outputs.SHA }} -f apps/admin/Dockerfile .
          docker push ${{env.REPOSITORY}}/eks-admin-demo:latest
          docker push ${{env.REPOSITORY}}/eks-admin-demo:${{ steps.vars.outputs.SHA }}

      - name: Build and Push User Image
        run: |
          docker build -t ${{env.REPOSITORY}}/eks-user-demo:latest -t ${{env.REPOSITORY}}/eks-user-demo:${{ steps.vars.outputs.SHA }} -f apps/users/Dockerfile .
          docker push ${{env.REPOSITORY}}/eks-user-demo:latest
          docker push ${{env.REPOSITORY}}/eks-user-demo:${{ steps.vars.outputs.SHA }}

      - name: Build and Push Auth Image
        run: |
          docker build -t ${{env.REPOSITORY}}/eks-auth-demo:latest -t ${{env.REPOSITORY}}/eks-auth-demo:${{ steps.vars.outputs.SHA }} -f apps/auth/Dockerfile .
          docker push ${{env.REPOSITORY}}/eks-auth-demo:latest
          docker push ${{env.REPOSITORY}}/eks-auth-demo:${{ steps.vars.outputs.SHA }}
